/**
 * Fixed coordinates for the hero scene.
 *
 * Written out rather than randomised so the layout is identical on the server
 * and the client — a random sky would hydrate into a different sky — and so the
 * constellation can be composed by eye instead of left to chance.
 */

/**
 * The bright points of the sky. These are the AI motif and the night sky at
 * once: in dark mode they read as stars joined into constellations, in light
 * mode as a neural net over an overcast afternoon. Same geometry, two
 * readings — which is why they aren't two separate sets of coordinates.
 */
export const NEURONS: { x: number; y: number; r: number }[] = [
  { x: 78, y: 62, r: 2.6 },
  { x: 156, y: 108, r: 1.9 },
  { x: 214, y: 48, r: 2.2 },
  { x: 292, y: 96, r: 3 },
  { x: 356, y: 42, r: 1.8 },
  { x: 430, y: 104, r: 2.4 },
  { x: 498, y: 56, r: 2.1 },
  { x: 566, y: 118, r: 2.8 },
  { x: 628, y: 52, r: 1.9 },
  { x: 704, y: 100, r: 2.5 },
  { x: 748, y: 44, r: 2 },
  { x: 120, y: 158, r: 1.7 },
  { x: 340, y: 150, r: 2.2 },
  { x: 610, y: 162, r: 1.8 },
];

/** Index pairs into NEURONS. Kept sparse so the sky reads as a net, not a mesh. */
export const SYNAPSES: [number, number][] = [
  [0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10],
  [0, 11], [1, 11], [3, 12], [5, 12], [7, 13], [9, 13], [11, 12], [12, 13],
  [2, 5], [6, 9],
];

/**
 * Background stars, filling the sky around the constellation above. Dark mode
 * only — a field of stars over a bright overcast afternoon would be nonsense,
 * so the CSS keeps these hidden in light mode.
 *
 * Generated by a pure function of index rather than Math.random() for the same
 * SSR/hydration reason as everything else here. The golden angle spreads them
 * without any repeating pattern the eye can lock onto; the y term keeps them
 * above the ridgeline, which starts around y=190.
 */
export const STARS: { x: number; y: number; r: number; delay: number; dur: number }[] =
  Array.from({ length: 46 }, (_, i) => ({
    x: (i * 137.508) % 800,
    y: 12 + ((i * 61.803) % 168),
    r: 0.5 + ((i * 7) % 5) * 0.24,
    delay: -((i * 1.7) % 9),
    dur: 3.2 + ((i * 11) % 7) * 0.55,
  }));

/**
 * Cloud shapes. Each is its own puff cluster rather than one shared blob at
 * different scales — a single repeated silhouette is exactly what made the
 * first version read as smudges instead of weather.
 *
 * Rendered twice — at x and x+800 — inside a group that drifts a full tile
 * width and loops, so the seam never shows: instance N's right edge is
 * instance N+1's left edge, by construction rather than by accident.
 */
export interface Cloud {
  x: number;
  y: number;
  scale: number;
  puffs: { dx: number; dy: number; rx: number; ry: number }[];
}

export const CLOUDS_FAR: Cloud[] = [
  {
    x: 90,
    y: 48,
    scale: 1.35,
    puffs: [
      { dx: -62, dy: 14, rx: 40, ry: 16 },
      { dx: -16, dy: -2, rx: 48, ry: 24 },
      { dx: 32, dy: 8, rx: 38, ry: 17 },
      { dx: 70, dy: 16, rx: 28, ry: 12 },
    ],
  },
  {
    x: 560,
    y: 58,
    scale: 1.4,
    puffs: [
      { dx: -66, dy: 12, rx: 38, ry: 15 },
      { dx: -20, dy: -4, rx: 48, ry: 22 },
      { dx: 26, dy: 6, rx: 40, ry: 18 },
      { dx: 66, dy: 15, rx: 26, ry: 11 },
    ],
  },
];

export const CLOUDS_NEAR: Cloud[] = [
  {
    x: 280,
    y: 100,
    scale: 1.55,
    puffs: [
      { dx: -80, dy: 16, rx: 44, ry: 16 },
      { dx: -28, dy: 0, rx: 54, ry: 26 },
      { dx: 28, dy: -6, rx: 50, ry: 24 },
      { dx: 74, dy: 10, rx: 40, ry: 16 },
    ],
  },
];

export const LIGHTNING_BOLT =
  'M232 6 L214 74 L242 70 L206 152 L228 96 L200 100 Z M214 74 L188 108 M228 96 L252 124';

export const SNOWFLAKES: { x: number; r: number; delay: number; dur: number }[] = [
  { x: 24, r: 1.6, delay: 0, dur: 11 },
  { x: 88, r: 1.1, delay: 2.4, dur: 14 },
  { x: 143, r: 2, delay: 5.1, dur: 9.5 },
  { x: 196, r: 1.3, delay: 1.2, dur: 13 },
  { x: 252, r: 1.7, delay: 6.8, dur: 10.5 },
  { x: 311, r: 1, delay: 3.6, dur: 15 },
  { x: 368, r: 1.9, delay: 8.2, dur: 12 },
  { x: 422, r: 1.4, delay: 0.9, dur: 10 },
  { x: 480, r: 1.7, delay: 4.7, dur: 13.5 },
  { x: 534, r: 1.1, delay: 7.5, dur: 11.5 },
  { x: 592, r: 2.1, delay: 2.1, dur: 9 },
  { x: 648, r: 1.3, delay: 5.9, dur: 14.5 },
  { x: 702, r: 1.6, delay: 3.1, dur: 12.5 },
  { x: 757, r: 1.2, delay: 7.9, dur: 10.8 },
];
